### DISCUSSION TITLE
Daily kWh usage?

### DISCUSSION THREAD

**Discussion by TommySharpNZ** [firstof9/openevse#105] [Q&A]
Is there a sensor that reports total kWh usage since midnight?

**Comment by firstof9** [comment]
There isn't one built into OpenEVSE.

You _can_ however create one from the `power` sensor (the one that reports the watts), by feeding that into the `integration` integration then feed that into a `utility meter`.

**Comment by firstof9** [comment]
If you need an example of how to set this up let me know.

**Comment by TommySharpNZ** [comment]
If it's not to much to ask then yes, I'd definitely appreciate some kind of example to improve my chance of success :-)

**Reply by firstof9** [reply]
I'll post what you need later today.

**Reply by firstof9** [reply]
```yaml
sensors:
  - platform: integration
    source: sensor.openevse_current_power_usage
    name: openevse_energy_consumption
    unit_prefix: k
    unit_time: h
```
Once you have this sensor setup you can add it via the `Config` -> `Devices & Services` -> `Helpers` -> `Utility Meter` and feed it the new `openevse_energy_consuption` sensor.
