### DISCUSSION TITLE
Missing Max Current automation

### DISCUSSION THREAD

**Discussion by andriuskr** [firstof9/openevse#35] [General]
Hello,

As there is no services for OpenEVSE integration, cannot find out how i can automate Max Current setting depending on whole home energy usage and (later) by solar power generation.

Any thought how to automate max current setting ?

**Comment by firstof9** [comment]
You can use a service under your automation action calling the `select` for `max_current` example:

```yaml
service: select.select_option
data:
  option: {{ max_current }}
target:
  entity_id: select.openevse_max_current
```
