### ISSUE TITLE
[Bug]: service/action OpenEVSE: Set charge limit : cannot set a variable as limit value for energy

### ISSUE THREAD

**Issue by ouinouin** [firstof9/openevse#405]
### The problem

Hi,
 while trying to call the set charge limit, i can only input  a fixed number, this seems counter intuitive since what we tend to do for this limit is to be able to be easily changed (by the mean of an input_number helper for example that is set on homeassistant by a template.
the field to input a number doesnt seem to accept this unlike the MQTT publish payload  for example that supports templating and so.
is there an easy way to make this field a "dynamic field" referring to a variable or being templatable ? 
![service set failure with input_number](https://github.com/user-attachments/assets/8e98b762-1d8c-4e1b-9b00-435657aae92f)

some further tests also shows that if a limit is already there, sending a limit will set the existing limit to 0kwh. is this a limitation by openevse code ? 
i guess this issue is the same for the SOC , the range etc etc (not enough meterial to try this.).

### What version of Home Assistant?

core-2024.11.2

### What version of OpenEVSE?

5.1.2

**Comment by firstof9** [comment]
Dev tools won't accept entities.

**Comment by ouinouin** [comment]
![image](https://github.com/user-attachments/assets/c2b5cee4-3245-4ae5-8594-33479f255adc)
i can put whatever value that is not a number, the automation wint be validated . the value is an input_number fabricated from the number helper in "entry" category in homeassistant
the below example is with a template that is working with an automation sending a mqtt payload (i know that in the case of mqtt the payload are strings, but i tried whaterver variable returning an int or a float and got the same results.
![image](https://github.com/user-attachments/assets/26adc5fc-e892-46c1-966e-c7038aa28869)

**Comment by firstof9** [comment]
No no, copy/paste yaml only, no screen shots of UI junk please.

**Comment by firstof9** [comment]
```yaml
alias: testev
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_number.evkwhoverride
    from: null
    to: null
conditions: []
actions:
  - action: openevse.set_limit
    metadata: {}
    data:
      type: energy
      auto_release: true
      value: {{ states('input_number.evkwhoverride')|int(0) }}
mode: single
```

**Comment by ouinouin** [comment]
@firstof9  : 
executing with the above yaml failed : 
```

xécuté : 19 novembre 2024 à 16:05:54
Erreur : expected int for dictionary value @ data['value']
Résultat :

params:
  domain: openevse
  service: set_limit
  service_data:
    type: energy
    auto_release: true
    value:
      '[object Object]': null
  target: {}
running_script: false

```

if i input a number like 1 2 3 etc with the same yaml , it works. i checked on the template editor , the {{ states('input_number.evkwhoverride')|int(0) }} outputs 10.
