### ISSUE TITLE
[Feature Request]: select.openevse_override_state

### ISSUE THREAD

**Issue by KipK** [firstof9/openevse#434]
### The feature

With a view to simplify UX, that would perhaps be better to replace the sensor.openevse_override_state by a select entity.
Doing the action logic inside the integration directly.

Here are my actions for the 3 buttons Active / Auto / Disabled:

* Active: 

```
tap_action:
              action: call-service
              service: openevse.set_override
              target:
                device_id: a273cedd6721ed05a9d6e41a3c1c757c
              data:
                state: active
```

* Auto:

```
tap_action:
  action: call-service
  service: openevse.clear_override
  target:
                device_id: a273cedd6721ed05a9d6e41a3c1c757c
```

* Disabled:

```
tap_action:
              action: call-service
              service: openevse.set_override
              target:
                device_id: a273cedd6721ed05a9d6e41a3c1c757c
              data:
                state: disabled
```
